apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nodejs
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
      #- cluster: nodejs
       # url: https://vc-8gqvedrvabptwavwjwq4.apps.aws-mumbai-eks.klusternetes.com
  template:
    metadata:
      name: nodejs
    spec:
      project: default
      source:
        repoURL: https://github.com/sai8465/nodejs-welcome.git
        targetRevision: HEAD
        path: nodejs
      destination:
        server: '{{url}}'
        namespace: default
