apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-kaniko-git
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: build
  serviceAccountName: argo
  volumes:
  - name: kaniko-secret
    secret:
      secretName: docker
      items:
        - key: .dockerconfigjson
          path: config.json
  templates:
  - name: build
    dag:
      tasks:
      - name: build
        templateRef:
          name: kaniko
          template: build-kaniko-git
          clusterScope: true
        arguments:
          parameters:
          - name: app_repo
            value: git@github.com:sai8465/nodejs-welcome.git
          - name: container_image
            value: sai8465/nodejs-welcome
          - name: container_tag
            value: "1.0.0"

